version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./:/home/node/.n8n
    environment:
      GENERIC_TIMEZONE: America/Sao_Paulo
    restart: unless-stopped
    networks:
      - n8n-network-test

networks:
  n8n-network-test:
    name: n8n-network-test  # Define um nome fixo para rede externa
    driver: bridge
